### PR TITLE
ensure clean imagify state before tagged smoke scenarios

### LINKED ISSUE #336: Update test to capture https://github.com/wp-media/wp-rocket/issues/7991
Version 3.20.3 should cause an error in debug.log with the following steps
1- fresh install and activate 3.20.3 zip
2- Access settings page (click on settings in admin bar) => we shouldn't see error /warning in debug.log

Note: 
- Manually checking this, it fails. However, e2e didn't fail for that.
- The goal here is that the smoke test should fail with a similar issue

### PR DESCRIPTION
**Pull request by hanna-meda**
# Description

Fixes #336 
This PR adds a new precondition hook that uninstalls Imagify when present for selected smoke tests.

## Type of change

- [ ] New feature (non-breaking change which adds functionality).
- [x] Bug fix (non-breaking change which fixes an issue).
- [x] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).
- [ ] Sub-task of #(issue number)
- [ ] Chore
- [ ] Release

### What was tested

- Verified tagged smoke scenarios trigger the new precondition hook that uninstalls Imagify when present.
- Verified non-tagged smoke scenarios are unchanged.
- Ran command `npm run test:smoke` with wpr 3.20.3 to make sure the error described in https://github.com/wp-media/wp-rocket/issues/7991 is now caught through smoke tests. 
Screenshot 2026-04-16 at 15 06 33

### How to test

Run `npm run test:smoke` with wpr 3.20.3 as `new_release`. Expected: Smoke tests that install the plugin and visit settings fail, with an error in debug.log.

### Affected Features & Quality Assurance Scope

- Smoke scenarios that install/activate WP Rocket and then visit settings or enable all settings.
- Hook execution flow for tagged smoke scenarios.

### Documentation

Added a new tag-scoped Before hook for selected smoke scenarios.
Hook checks whether Imagify is installed and uninstalls it if present.
Scope is limited using tag expression to avoid impacting unrelated scenarios.

### New dependencies

None.

### Risks

Extra setup time for tagged scenarios if Imagify is installed.
Tag drift if future smoke scenarios need the same precondition but are not tagged.

Mitigations:
Hook is narrowly scoped via tags.

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification
N/A

# Additional Checks
- [x] In the case of complex code, I wrote comments to explain it.
- [x] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [ ] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

File: src/support/hooks.ts [hunk 1]
```diff
@@ -90,6 +90,15 @@ BeforeAll(async function (this: ICustomWorld) {
     }
 });
 
+/**
+ * Before each smoke scenario requiring a clean environment, ensures Imagify is not installed.
+ */
+Before({ tags: '@smoke and @requires-clean-imagify and not @imagify-compatibility' }, async function (this: ICustomWorld): Promise<void> {
+    if (await isPluginInstalled('imagify')) {
+        await uninstallPlugin('imagify');
```
[the remark this answers is not in the document]
Comment (hanna-meda) [reply src/support/hooks.ts]: @copilot This is valid in general, but our E2E runs are on external servers only (remote SSH on nginx/apache test sites). In that environment, [commands.ts:79](https://github.com/wp-media/wp-rocket-e2e/blob/2db20176525860dcb7bbc6f48b0de9105caac8bc/utils/commands.ts#L79) returns a boolean and the precondition works as expected. We are keeping this PR scoped and can address local/docker consistency separately if needed.

File: src/support/hooks.ts [hunk 2]
```diff
@@ -90,6 +90,14 @@ BeforeAll(async function (this: ICustomWorld) {
     }
 });
 
+/**
+ * Before each scenario tagged with @requires-clean-imagify, except those also tagged with
+ * @imagify-compatibility, ensures Imagify is not installed.
+ */
+Before({ tags: '@requires-clean-imagify and not @imagify-compatibility' }, async function (this: ICustomWorld): Promise<void> {
```
Comment (Mai-Saad) [inline src/support/hooks.ts:97]: if we need this run before smoke test , why not just use @smoke instead of @requires-clean-imagify?

Comment (hanna-meda) [reply src/support/hooks.ts:97]: @Mai-Saad, I used requires-clean-imagify so this hook can be reused beyond smoke. It is currently applied only in smoke, but the precondition itself is not smoke-specific.

**Comment by hanna-meda** [comment]
Smoke results with 3.21.1 as new release (all green):
Screenshot 2026-04-23 at 16 32 55

@Mai-Saad

**Review by wordpressfan — APPROVED** [review]

**Comment by Mai-Saad** [comment]
image

**Review by Mai-Saad — APPROVED** [review]
